[package]
name = "LGB"
version = "0.1.0"
authors = ["Linkfy <linkstudios@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.15.3"
json = "0.12.1"